library(Seurat)
merged.gut<-readRDS("/home/fs01/jjv4001/integrated_iter_2_seurat.rds")
merged.gut <- subset(merged.gut, idents="EECs")
#data normalization
merged.gut <- NormalizeData(merged.gut, normalization.method="LogNormalize", scale.factor=10000)
merged.gut <- FindVariableFeatures(merged.gut, selection.method="vst", nfeatures=400)
merged.gut <- ScaleData(merged.gut, features=rownames(merged.gut))
merged.gut <- RunPCA(merged.gut , features=VariableFeatures(object=merged.gut))
merged.gut <- RunUMAP(merged.gut, dims=1:10, n.components=3)
merged.gut@misc$umap3d <- merged.gut@reductions$umap
merged.gut <- RunUMAP(merged.gut, dims=1:10, reduction="pca")
merged.gut <- FindNeighbors(merged.gut, dims=1:10)
Kcell<-WhichCells(merged.gut, expression=GIP >4)
merged.gut$gene <- ifelse(colnames(merged.gut) %in% Kcell, "K cell","gene-neg")
write.csv(merged.gut@meta.data, "Kcell.csv")
MXAcell<-WhichCells(merged.gut, expression=GHRL >4 & MLN>4)
merged.gut$gene <- ifelse(colnames(merged.gut) %in% MXAcell, "M/X/A cell", "gene-neg")
write.csv(merged.gut@meta.data, "MXAcell.csv")
Icell<-WhichCells(merged.gut, expression=CCK >4)
merged.gut$gene <- ifelse(colnames(merged.gut) %in% Icell, "I cell", "gene-neg")
write.csv(merged.gut@meta.data, "Icell.csv")
Dcell<-WhichCells(merged.gut, expression=SST >4)
merged.gut$gene <- ifelse(colnames(merged.gut) %in% Dcell, "D cell", "gene-neg")
write.csv(merged.gut@meta.data, "Dcell.csv")
Lcell<-WhichCells(merged.gut, expression=GCG >4 & PYY>4)
merged.gut$gene <- ifelse(colnames(merged.gut) %in% Lcell, "L cell", "gene-neg")
write.csv(merged.gut@meta.data, "Lcell.csv")
Ncell<-WhichCells(merged.gut, expression=NTS >4)
merged.gut$gene <- ifelse(colnames(merged.gut) %in% Ncell, "N cell", "gene-neg")
write.csv(merged.gut@meta.data, "Ncell.csv")
ECcell<-WhichCells(merged.gut, expression=TPH1 >4)
merged.gut$gene <- ifelse(colnames(merged.gut) %in% ECcell, "EC cell", "gene-neg")
write.csv(merged.gut@meta.data, "ECcell.csv")
Idents(merged.gut)<-merged.gut$gene

saveRDS(merged.gut, file=paste("EEChormoneassignment", sep=""))